% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrreprt}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother

\ifLuaTeX
  \usepackage{luacolor}
  \usepackage[soul]{lua-ul}
\else
  \usepackage{soul}
\fi

% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={RMS textbook},
  pdfauthor={Pilot, Lucas, and Murray},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{RMS textbook}
\author{Pilot, Lucas, and Murray}
\date{2025-10-28}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}

\bookmarksetup{startatroot}

\chapter*{Preface}\label{preface}
\addcontentsline{toc}{chapter}{Preface}

\markboth{Preface}{Preface}

This is a book intended to be used for Dr.~Pilot's PSY 303 course at the
University of Southern Indiana, home of the screaming eagles.

This book was a collaboration between Dr.~Pilot, Liam Murray, and Jacob
Lucas.

\bookmarksetup{startatroot}

\chapter{Introduction}\label{introduction}

This is a book created from markdown and executable code.

See Knuth (1984) for additional discussion of literate programming.

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1} \SpecialCharTok{+} \DecValTok{1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2
\end{verbatim}

\bookmarksetup{startatroot}

\chapter{Fundamentals of R}\label{fundamentals-of-r}

\section{2.1 Introduction}\label{introduction-1}

This chapter will go over the fundamental tools you will need in order
to work in R and to create projects and to experiment with the building
blocks of Rstudio. If you have not already gone to chapter one that
teaches you how to set up Rstudio do that now.

\begin{itemize}
\item
  How to use packages and what you will need to do in order to update
  them.
\item
  How to create and manipulate data.
\item
  How to use functions, objects, and pipes.
\item
  Common errors and different ways to deal with them.
\item
  And the main types of data that you will be running into in Rstudio.
\end{itemize}

\section{2.2 Rstudio Overview}\label{rstudio-overview}

Once you open Rstudio you might notice that there are four different
panes on your screen that each look different from the other. Although
it might look overwhelming these panes are all important when operating
in Rstudio and will all be used

\subsection{2.2.1 Console Frame}\label{console-frame}

The console frame is the \textbf{bottom left frame on your screen}. This
is where you will be viewing some of your code. You can also see outputs
from your code directly in this frame and is one location of where you
will be trouble shooting as well. Think of this frame as a chat box in R
in order to see behind the scenes of what you will be running. You
should make note that the console is like a scrap piece of paper or and
etch an sketch its a great place to do some troubleshooting or viewing
data through the \texttt{glimpse()} function but \textbf{any work you do
here will not be saved.} The console is also next to the terminal which
is the tab right next to it. \textbf{They both can run commands but are
different in nature}.The console is intended to run commands that work
mainly inside Rstudio itself. The terminal however runs systems commands
like something you do on your computer.

\pandocbounded{\includegraphics[keepaspectratio]{images/R_console_screenshot.png}}

\subsection{2.2.2 Source Frame}\label{source-frame}

The source frame or editor frame is \textbf{the top left frame} on your
screen. This frame is the primary location of where you will be doing
your work and typing all of your code. When you create a new code chunk
you will do that in the source frame. You should be able to see all the
lines and numbers of each code line. You can also save and open new
documents and files at the farthest top left corner of this frame.
Opening your Rmarkdown files like you created in \textbf{chapter 1} is a
great way to practice using the source frame and where you will do this.

\pandocbounded{\includegraphics[keepaspectratio]{images/source_screenshot_example.png}}

\subsection{2.2.3 Environment/History}\label{environmenthistory}

The environment or history frame can be seen in \textbf{the top right
frame on your screen.} This is where you can view current objects that
you have created which we will discuss further in the chapter as well as
data sets and where you can track your steps by viewing the command
history that you have run.

\pandocbounded{\includegraphics[keepaspectratio]{images/Environment_screenshot_example.png}}

\subsection{2.2.4 Files/Packages}\label{filespackages}

The last frame on \textbf{the bottom right is your files and packages}
frame. This frame is more of a window into your own computer itself in
the sense that you are able to view the packages and files that you have
on your current computer. You can also use it to check any plots you
might have and to read any documents on your computer as well. You only
will need to download a package one time but whenever you open Rstudio
you will need to load it up every time.

\pandocbounded{\includegraphics[keepaspectratio]{images/files_screenshot_example.png}}

\textbf{Suggestion}: If you wish to change the layout of your frames to
customize it simply click tools at the top of your computer then global
options then to pane layout to customize the layout to whatever is the
best for you.

\section{2.3 Packages and the
tidyverse}\label{packages-and-the-tidyverse}

Now that you are familiar with where you can view and access your
packages we will now take a closer look as to what they are and
different tips fro them as well as introducing you to a very useful
package that will make writing code much easier and it is called the
tidyverse.

\subsection{2.3.1 What is a package?}\label{what-is-a-package}

You might be wondering how we are going to be using something that you
typically get in the mail on your computer. In R a package is where R
gets its main power from. We have packages because just like in real
life they contain something. In R packages can contain a multitude of
functions, data, and documents.

\subsection{2.3.2 Installing and finding
packages}\label{installing-and-finding-packages}

Whenever you want to install a package you will have to run a command.
When you are working in a document you will need to load your packages
each time or else \textbf{your code will not run because the package has
not been reloaded.} You can install packages by going to your console
frame in the bottom left. Once you are there you will type the following
code. Do not be afraid if you see a warning in yellow that is perfectly
normal.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"tidyverse"}\NormalTok{)}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"dplyr"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Then to load it into your active session the first thing you always want
to do is to load it into your session. You will want to do this by
running the following in your source frame or the top left. We do this
by using the the \textbf{library} function which calls up any package
that you have installed it will not work if you do not have the package
installed.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

Once you have successfully loaded the tidyverse into your current
session you should get the following result in your console:

\pandocbounded{\includegraphics[keepaspectratio]{images/Tidyverse_load_example.png}}

\textbf{THIS IS OK IT MEANS YOU HAVE SUCCESFULLY LOADED YOUR PACKAGE}

Now sometimes you will need to update your packages because if you don't
it can cause them to not load and your code will not run. If this
happens all you will have to do is run this code.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{update.packages}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

To see what packages you have installed you can either go to the bottom
right pane and find the packages tab to find a list of all packages and
which are installed. Or you could also run this code.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{installed.packages}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\subsection{2.3.3 The Tidyverse}\label{the-tidyverse}

Now that you have successfully installed the \textbf{tidyverse} we can
examine it and what it does. When thinking about the tidyverse the best
way to explain it is think of it like a universe. A universe is a space
that contains different things like planets which contain different
things like people. Well just like a universe the tidyverse contains a
large amount of packages inside of it that are meant to make using R
easier and work more efficiently. All the packages inside the tidyverse
all share a common philosophy and syntax. Think of it like the world
having america and how we all share a common philosophy and syntax. The
packages in the tidyverse work the same way. Because all of these
functions use the same grammar it makes it easier for us to read R code.
Take a look at this example

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}

\CommentTok{\# Example of data transformation}
\NormalTok{starwars }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(name, height, mass, species) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(species }\SpecialCharTok{==} \StringTok{"human"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(mass))}
\end{Highlighting}
\end{Shaded}

\section{2.4 Functions}\label{functions}

Now that we are able to successfully load up packages we can start
looking at some functions. A \textbf{function} is a command that begins
an action this is a basic example of a function

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{function\_name}\NormalTok{(}\AttributeTok{argument1 =}\NormalTok{ value1, }\AttributeTok{argument2 =}\NormalTok{ value2)}
\end{Highlighting}
\end{Shaded}

\subsection{2.4.1 Applied Functions}\label{applied-functions}

The function is made up of two arguments that we give values to.

Next we can look at a basic function called the \textbf{combine}
function or it can be viewed as this \texttt{c()}. It takes every value
we have in the function and applies it to all of them. This can be used
for mathematical purposes when using Rstudio like a calculator. Lets
take a look at an example

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3
\end{verbatim}

As you can see we get the output after and we can see the answer is 3.
We ran this function and all the values were applied to each other while
we also utilized the \textbf{mean} function combining two functions.

\subsection{2.4.2 Creating Functions}\label{creating-functions}

Creating your own function is a very useful skill because it allows you
to easily apply values to data without you having to type it out over
and over again. In order to create a function you must name it then
assign it a value by using the \texttt{\textless{}-} symbol. This
assigns whatever you write to that name which then should appear in the
top right frame or your environment frame.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plus\_two }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  x }\SpecialCharTok{+} \DecValTok{2}
\NormalTok{\}}

\FunctionTok{plus\_two}\NormalTok{(}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 7
\end{verbatim}

As you see we created the function \texttt{plus\_two} Which will take
whatever is in our function and add 2 to it so when we use the function
and put 5 in there it takes 5 and already adds the two to it.

\subsection{2.4.3 Assignment operator}\label{assignment-operator}

Whenever we want to assign a value to something we need to use the
\texttt{\textless{}-} symbol. This will then take whatever we assign to
the value we create. As you can see in the example above the function we
created was assigned to the value \texttt{plus\_two} because we used the
assignment operator to give it that value.

\subsection{2.4.4 Arguments}\label{arguments}

When we are using functions we must also know that we are dealing with
arguments as well. An argument is the information that we put into a
function so the function knows what to do with it. So think of the
function like a machine and the arguments are the ingredients that we
give it.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(}\AttributeTok{x =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

As you can see here the mean is the function we are using and the
argument is everything inside of the parenthesis.

\section{2.5 Creating Data}\label{creating-data}

There are several different ways that we can create data which is
important when we want different functions

\subsection{2.5.1 Vectors}\label{vectors}

A \textbf{vector} is a simple data structure that holds elements of the
same kind. So if we want to combine a bunch of names we can use a vector
to do so but they need to all be the same type of data. Which we will go
over the different types of data later in the chapter. Here are some
simple basic examples of a vector

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{numbers }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{7}\NormalTok{)}
\NormalTok{names }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Adam"}\NormalTok{, }\StringTok{"Steven"}\NormalTok{, }\StringTok{"James"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now once we have these saved we can use them again if we want since we
have combined them all into one vector.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{numbers}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1 2 3 4 5 6 7
\end{verbatim}

\subsection{2.5.2 Data Frames}\label{data-frames}

A \textbf{data frame} is a different way of creating data. When you use
a data frame think of it like a window frame. In a data frame the data
is arranged into a rectangular shape and uses rows and columns. The
columns in a data frame are called \textbf{variables} and the rows in
our data frame are called \textbf{observations}. Now we can use data
frames to combine two different types of data into one output.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{name =} \FunctionTok{c}\NormalTok{(}\StringTok{"James"}\NormalTok{, }\StringTok{"Henry"}\NormalTok{),}
  \AttributeTok{age =} \FunctionTok{c}\NormalTok{(}\DecValTok{21}\NormalTok{,}\DecValTok{67}\NormalTok{),}
  \AttributeTok{sport =} \FunctionTok{c}\NormalTok{(}\StringTok{"Baseball"}\NormalTok{, }\StringTok{"Soccer"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   name age    sport
1 James  21 Baseball
2 Henry  67   Soccer
\end{verbatim}

You can see our output of how the data is arranged into the order that
we make it to where the same location is applied so that they go in
order. You can also see at the bottom of the output where it displays
the number of rows that we have.

\subsection{2.5.3 Tribbles}\label{tribbles}

A tribble is short for transposed tibble and it is a different way to
create small data frames.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tibble)}

\NormalTok{people }\OtherTok{\textless{}{-}} \FunctionTok{tribble}\NormalTok{(}
  \SpecialCharTok{\textasciitilde{}}\NormalTok{name,   }\SpecialCharTok{\textasciitilde{}}\NormalTok{age, }\SpecialCharTok{\textasciitilde{}}\NormalTok{city,}
  \StringTok{"James"}\NormalTok{,  }\DecValTok{21}\NormalTok{,   }\StringTok{"Evansville"}\NormalTok{,}
  \StringTok{"Hunter"}\NormalTok{, }\DecValTok{38}\NormalTok{,   }\StringTok{"Toledo"}
\NormalTok{)}
\NormalTok{people}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 2 x 3
  name     age city      
  <chr>  <dbl> <chr>     
1 James     21 Evansville
2 Hunter    38 Toledo    
\end{verbatim}

Now you can see our tribble fully completed with both rows and columns
where you can see in the bottom of the output that the tribble shows the
rows. It also tells us the type of data that we are seeing in the output
which you will learn more about later in the chapter.

\subsection{2.5.4 Glimpse}\label{glimpse}

When you want to examine the characteristics of your data you can use
glimpse to get more information about it. It provides the full data for
your set and gives all the details you could need.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(people)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Rows: 2
Columns: 3
$ name <chr> "James", "Hunter"
$ age  <dbl> 21, 38
$ city <chr> "Evansville", "Toledo"
\end{verbatim}

Look at the output above you can see next to name the
\texttt{\textless{}chr\textgreater{}} that means the column contains
data that is characters. The one below that is the
\texttt{\textless{}dbl\textgreater{}} so you can see that is double
data. This shows us that vectors simple a column of names and values
that are the same type.

\section{2.6 Objects}\label{objects}

In R the only thing we use are objects and a object can be data, a
function or even models that we need. In order to assign a object we use
the \texttt{\textless{}-}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}} \DecValTok{67}
\NormalTok{y }\OtherTok{\textless{}{-}} \StringTok{"Good Morning"}
\end{Highlighting}
\end{Shaded}

\subsection{2.6.1 Listing objects}\label{listing-objects}

If you ever want to see what your current objects are you can always
look in your environment frame to see it. You can also use the list
function \texttt{ls()} to see this as well.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ls}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\section{2.7 The pipe}\label{the-pipe}

Now we will be working with the pipe or
\texttt{\textbar{}\textgreater{}}. The pipe is a very important tool
because it works kind of like a river with bridges. Usually in R when we
run multiple functions we would have to think of the output like a boat
going through a river. Normally we would have to manually open each
bridge in order for it to pass through to the next part of the river.
The pipe makes it easier for us by doing that automatically. So whenever
we are running multiple functions in a code chunk we use the pipe to
channel the output right into the next function without having to do the
work ourselves. In the tidyverse the pipe is represented as
\texttt{\%\textgreater{}\%} which can be easily created with the
shortcut \textbf{\emph{command + shift + m.}} Now lets look at an
example of how the pipe works.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(cyl) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{mean\_mpg =} \FunctionTok{mean}\NormalTok{(mpg))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{images/car_output.png}}

You can see in the output now that in our pipe we took the car data set
then funneled in the function of grouping cars by their cylinders then
taking that output and funneling it into finding the average miles per
gallon which creates our final output.

Now try running the same code without the use of the pipe and see if it
still works.

\section{2.8 Types of data}\label{types-of-data}

There are different types of data in R and it is important to be able to
distinguish the differences because we work with different types in
different ways so being able to tell them apart will help us better
interpret data.

\subsection{2.8.1 Numeric data}\label{numeric-data}

Numeric data is the type of data that we see that represents whole
numbers. These are pretty common and are just regular numbers that can
be represented differently. When looking at an output in R we can see if
the data we are looking at is numeric by looking for how it is
abbreviated which is by \texttt{num}. Whenever we see a column whit this
title we know the data in that column is numeric. You can use the
\texttt{typeof()} function in R to see exactly what type of data you are
dealing with.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{typeof}\NormalTok{(}\DecValTok{42}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "double"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{typeof}\NormalTok{(}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "logical"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{typeof}\NormalTok{(}\StringTok{"jack"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "character"
\end{verbatim}

\subsection{2.8.2 Character data}\label{character-data}

Character data is words that we use in R that are not functions but
represent something in the data we are dealing with. These could be
examples like names in a data set that represent something. It is
important to note though we can tell if the data is a character because
it must always be in \texttt{"".} This shows that it is just text we are
dealing with and not some function. The abbreviation for character data
in R is \texttt{chr}. So whenever you see a column with \texttt{chr} you
know the data in it is character data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{    my\_vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"apple"}\NormalTok{, }\StringTok{"banana"}\NormalTok{, }\StringTok{"cherry"}\NormalTok{)}
    \FunctionTok{str}\NormalTok{(my\_vector)}
\end{Highlighting}
\end{Shaded}

\subsection{2.8.3 Logical data}\label{logical-data}

Logical data is a type of Boolean data in the sense that it can only
represent one of two values. This means that when we look at logical
data we are looking to see if something is either true or false. Kind of
like in real life when we use logic to see if we believe something or
not. So in R logical data will be represented as either \texttt{TRUE} or
\texttt{FALSE}. It is important that they are all capitalized so they
cannot be confused for something else. The abbreviations in R are simple
because it will either be \texttt{T} or \texttt{F}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Assigning logical values using full names}
\NormalTok{bool1 }\OtherTok{\textless{}{-}} \ConstantTok{TRUE}
\NormalTok{bool2 }\OtherTok{\textless{}{-}} \ConstantTok{FALSE}

\CommentTok{\# Assigning logical values using abbreviations}
\NormalTok{bool3 }\OtherTok{\textless{}{-}}\NormalTok{ T}
\NormalTok{bool4 }\OtherTok{\textless{}{-}}\NormalTok{ F}
\end{Highlighting}
\end{Shaded}

\subsection{2.8.4 Factor data}\label{factor-data}

In R we refer to factor data as the type of categories that variables
are stored as a factor. It works with variables that have a fixed and
already known set of possible values. We use factor data differently
depending on the data we are trying to use. We use \texttt{factor()} to
create a new factor from a vector. We use \texttt{as.factor()} to move
an object like a character list into a vector. \texttt{is.factor()} is
when we want to check if an object is already a factor.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(}\FunctionTok{factor}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Low"}\NormalTok{), }\StringTok{"High"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\subsection{2.8.5 Double data}\label{double-data}

Double data is how we refer to data that are numbers but not whole
numbers. Not to be confused with numeric data double data deals with
decimals that are numbers. This can be represented as \texttt{dbl}. So
this tells us that whenever we see a column that has that list it means
that we are dealing with numbers but they are decimals and not whole
numbers

\section{2.9 Tips and trouble shooting}\label{tips-and-trouble-shooting}

When working with R there is always going to be something that will end
up needing fixing or something will go wrong and you have no idea what
to do. That is OK because there are a few different ways to figure
things out when you need help.

\subsection{2.9.1 ? Tool}\label{tool}

The question mark tool is a great too that can help explain anything you
need. Lets say for example you don't know what a mean is. You can type
in \texttt{?mean} and the help tab in your bottom right frame will open
with whatever you need. It provides arguments and explanations as it is
a great tool to help you figure things out.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{?mean}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{images/help_info_sc.png}}

\subsection{2.9.2 Help}\label{help}

The help function is another way to get info on objects you might be
struggling with. It works the same as the question and can give you more
information on it.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{help}\NormalTok{(}\StringTok{"mean"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{2.9.3 Traceback}\label{traceback}

Whenever we are working in R sometimes we might get an error. This can
be confusing because R doesn't always tell you where you made this error
it usually tells you what is wrong and when you are writing lots of code
it can be difficult to find where you went wrong. Well you can use the
\texttt{traceback()} function to find exactly where your code stopped
working.

\section{2.10 Practice}\label{practice}

Now that you learned the basic fundamentals of R and operating inside of
it here are some practice problems to make yourself more comfortable
with working in R

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Create a \texttt{tribble()} with four of your friends names, ages, and
  cities they are from
\item
  Use \texttt{glimpse()} to inspect the data
\item
  Write a function that doubles any number
\item
  Use the pipe to select certain columns
\item
  Find and list each columns type of data
\end{enumerate}

\bookmarksetup{startatroot}

\chapter{What are Behavioral
Sciences}\label{what-are-behavioral-sciences}

\section{What is Psychology?}\label{what-is-psychology}

Psychology is the study of behavior and mental processes.

Psychology is rooted in philosophical thought and exploration.

Wilhelm Wundt created the first psychology lab.

Your Lineage:

Wundt -\textgreater{} Titchener -\textgreater{} Boring -\textgreater{}
Tulving -\textgreater{} Habib -\textgreater{} Me-\textgreater You

Behavioral research is involved in a multitude of different disciplines;
like Social work, Criminology, and Communication.

\section{Goals of Behavioral
Research}\label{goals-of-behavioral-research}

\ul{\textbf{Describe}}

Patterns of behavior, thought, and emotion.

\ul{\textbf{Predict behavior}}

Focus on developing equations that predict behavior.

\ul{\textbf{Explain behavior}}

Develop theoretical explanations for patterns of behavior.

\section{Two Schools of Research}\label{two-schools-of-research}

\ul{\textbf{Basic Research}}

Research conducted without regard for whether the knowledge is
immediately applicable

\emph{Ex. Does drinking coffee influence long-term memory?}

\ul{\textbf{Applied Research}}

Research conducted to find solutions for problems rather than to enhance
general knowledge

\emph{Ex. Does giving paid maternal/paternal leave increase employee
happiness at USI?}

\section{Scientific Approach}\label{scientific-approach}

\ul{\textbf{Systematic Empiricism}}

Observing behavior with clear guidelines for the purpose of drawing
conclusions.

\ul{\textbf{Public Verification}}

Allows others to replicate and discuss your findings.

\ul{\textbf{Solvable Problems}}

Research questions must be solvable with the current technology.

\emph{Examples of currently unsolvable problems: Whether Freud's
``unconscious'' exists, angels, souls, quantum theory?, vampires,
fairies}

\section{Purpose of Behavioral
Research}\label{purpose-of-behavioral-research}

\ul{\textbf{Detect}}

Discover and document new phenomena.

\ul{\textbf{Explain}}

Develop and evaluate theories that explain phenomena.

\section{How to Explain}\label{how-to-explain}

\ul{\textbf{Theory}}

Describes relationships between ideas.

\emph{Ex. Theory of Multiple Intelligences- Gardner suggests that there
are 8-10 distinct modalities of intelligence instead of one general
factor.}

Example: Theory of Evolution

\ul{\textbf{Model}}

A representation of a process.

\emph{Example: Assortative Mating Model-People tend to marry a partner
who is has similar interests, lives close, makes a similar amount of
money.}

\section{How to create a hypothesis}\label{how-to-create-a-hypothesis}

Hypothesis

An idea suggested as a way to explain a phenomena.

Post-hoc

Explanations made after the fact.

A priori

Predictions made before experimentation.

All hypotheses must be falsifiable, able to be unsupported, or shown to
be false.

\section{What is a variable?}\label{what-is-a-variable}

A variable is something that you measure.

Two ways to define variables:

Conceptual definition

A dictionary definition.

Ex: Drunk = affected by alcohol to the extent of losing control of one's
faculties or behavior.

Operational definition

Definition that specifies precisely how a concept is measured, think
about behaviors you can see.

Ex. Drunk = Blood Alcohol Content over .08.

\section{Proof, Disproof, and
Progress}\label{proof-disproof-and-progress}

Scientists do not prove anything, they find information that supports
hypotheses.

Scientists may disprove.

\emph{Example: How would one disprove the statement ``Unicorns do not
exist.''? They would find a unicorn.}

Scientific progress depends on replication and accumulated evidence.

\section{Research Strategies}\label{research-strategies}

\ul{\textbf{Descriptive}}

Describes behavior, thoughts, or feelings.

\ul{\textbf{Correlational}}

Investigates relationship between two or more variables.

\ul{\textbf{Quasi-experimental}}

Examines naturally occurring variables.

\ul{\textbf{Experimental}}

Determines whether certain variables cause changes.

Non-human animals can be studied in controlled conditions, for extended
periods of time, and can be utilized in many types of research
inappropriate for human beings.

\bookmarksetup{startatroot}

\chapter{How to plan an experiment}\label{how-to-plan-an-experiment}

\section{Experimental Research}\label{experimental-research}

Allows us to study causes of behavior.

\section{Three components of Experimental
Research}\label{three-components-of-experimental-research}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Manipulate a variable

  \begin{itemize}
  \tightlist
  \item
    Exercise experimental control
  \end{itemize}
\item
  Systematically put participants in groups

  \begin{itemize}
  \tightlist
  \item
    Ensure equivalent groups
  \end{itemize}
\item
  Control extraneous variables

  \begin{itemize}
  \tightlist
  \item
    Make sure factors that are unimportant don't influence results
  \end{itemize}
\end{enumerate}

\section{Independent variable (IV)}\label{independent-variable-iv}

The variable that the researcher manipulates. All experimental research
must have AT LEAST one. Researchers can manipulate the environment, the
instructions, or they may use an invasive variable (like giving someone
a caffeine pill).

Must have at least 2 levels

\emph{Ex. Temperature may have two levels; hot and cold}

\section{Subject (Participant)
Variables}\label{subject-participant-variables}

Based off of a personal characteristic. Something you cannot manipulate
in the lab.

\emph{Ex. Ethnicity/Race, Hob}bies

\section{Evaluating Your Independent
Variable}\label{evaluating-your-independent-variable}

A bad independent variable can result in a failed experiment.

\textbf{Pilot Study}

Test your experiment on a small group of people to ensure that it works.

\textbf{Manipulation Check}

Done to ensure that the level of your IV manipulation is strong enough.

\emph{Ex. Is 5mg of caffeine enough or should I use 10mg?}

\section{Dependent Variable}\label{dependent-variable}

The variable a researcher measures.

Experiments must have AT LEAST one.

\emph{Ex. Heart rate, response to questionnaire, performance on test}

\section{Groups in an Experiment}\label{groups-in-an-experiment}

\textbf{Experimental}

The group that receives the independent variable manipulation.

\emph{Ex. In a study about sleep, this group is required to stay awake
for 2 days.}

\textbf{Control}

The group that is not exposed to any independent variable manipulation.

\emph{Ex. In the same sleep study, this group sleeps however much they
usually sleep.}

\section{Assigning Participants}\label{assigning-participants}

\textbf{Simple Random Assignment}

Everyone has an equal chance of being assigned to any group/condition.

\emph{Ex. Roll dice}

In this situation people with any attribute are equally likely to be in
either group.

\textbf{Matched Random Assignment}

Participants are matched into homogeneous blocks. Participants in each
block are then randomly assigned to conditions.

In this situation conditions will be similar along specific dimensions.

\section{Within Subject Designs (repeated
measures)}\label{within-subject-designs-repeated-measures}

Participants are exposed to ALL conditions in an experiment.

No need for random assignment.

Ex\emph{. In an experiment testing a new drug all participants receive
all doses of the drug (5mg, 10mg, 15mg)}

\textbf{Pros}

More powerful

\textbf{Cons}

Order Effects

\section{Power}\label{power}

The ability to detect IV effects.

Requires fewer participants.

\section{Order Effects}\label{order-effects}

\textbf{Carryover effects}

One condition influences the following condition.

\textbf{Practice effects}

Participants have learned how to perform from previous experimental
trials.

\textbf{Fatigue effects}

Participants are tired, bored, have no energy over time.

\textbf{Sensitization}

Participants realize the hypothesis being tested and do not perform
naturally.

\textbf{Counterbalancing}

can be used to correct for order effects.

A researcher presents the levels of the IV in different orders for
different participants.

\subsection{Between-Subjects Design (Independent
Measures)}\label{between-subjects-design-independent-measures}

Participants experience only one condition of the IV.

Typically requires random assignment.

\emph{Ex. In an experiment testing a new drug each participant will
receive only one of the three levels of drug dosage (5mg or 10 mg or 15
mg).}

\section{Experimental Control}\label{experimental-control}

\textbf{Treatment effect}

Systematic differences due to the IV

\textbf{Confounds}

Variable other than the IV that differs systematically between
conditions.

Confounds invalidate your experiment because, if confounds are present,
it is unclear whether the observed differences are due to the IV or the
confound.

Must be eliminated to draw accurate conclusions.

\textbf{Error}

Unsystematic effects due to extraneous (uncontrolled) variables.

\section{Sources of Error}\label{sources-of-error}

Individual Differences

Transient states

Environmental factors

Differential treatment

Measurement error

\section{Types of Validity}\label{types-of-validity}

\textbf{Internal Validity}

Degree to which we can draw accurate conclusions about the effects of
the IV

Gain internal validity when all confounds are eliminated and you can
conclude that the observed differences were due to the IV.

Has experimental control.

\textbf{External Validity}

Inverse relationship with internal validity

The greater experimental control in your experiment, the less likely it
will be externally valid or generalizable to the ``real world''.

Internal validity is more critical and desirable than external validity.

\section{Threats to internal
validity}\label{threats-to-internal-validity}

\textbf{Biased assignment of participants}

Occurs when random assignment isn't possible or doesn't produce
equivalent groups.

\textbf{Differential attrition}

Participants drop out of the experiment differently across levels of the
IV.

\textbf{Demand Characteristics}

Participants perform in the way they believe the experimenter wants them
to.

\textbf{Placebo Effects}

Change as the result of the mere suggestion of change.

\textbf{Pretest sensitization}

Exposure to pretest affects one IV level differently than another

\textbf{History}

External events that participants experience affect one level of the IV
differently than another

\textbf{Experimenter expectancy effects}

Experimenter with certain expectations interacts with participants
differently

\subsection{Reducing threats to
validity}\label{reducing-threats-to-validity}

\textbf{Double Blind Procedure}

The researcher administering the IV and the participant both do not know
what level of the IV is being administered.

Can eliminate expectancy effects and demand characteristics

\bookmarksetup{startatroot}

\chapter{Measuring behavior}\label{measuring-behavior}

\section{Types}\label{types}

\begin{itemize}
\item
  Observational
\item
  Physiological
\item
  Self-report
\end{itemize}

\section{Scales of Measurement}\label{scales-of-measurement}

\subsection{Nominal Scales}\label{nominal-scales}

Numbers are assigned as labels for characteristics or behaviors.

Provides the least amount of information.

\emph{Ex. Jersey Number}

\subsection{Ordinal Scale}\label{ordinal-scale}

Rank ordering of people's behaviors or characteristics.

Doesn't specify the distance between participants on the variable being
measured.

\emph{Ex. Sizes at a fast food restaurant: baby, small, medium, large,
ex large, super size, super duper size}

\subsection{Interval Scale}\label{interval-scale}

Equal distance between the numbers reflect equal differences between
participants

Does not have a ``true'' zero point

\emph{Ex. Temperature, IQ score}

\subsection{Ratio Scale}\label{ratio-scale}

Has a ``true'' zero point.

Provides greatest amount of information.

Should be used when possible.

\emph{ex. duration, weight, accuracy}

\section{Central Tendency}\label{central-tendency}

A descriptive measure which represents the entire distribution of scores
(mean, median, mode).

\textbf{Goal:} Find a single value that is representative of all the
data.

Can condense large data set into a single value.

Allows comparison of 2 or more data sets using the central tendency.

\subsection{The Mean}\label{the-mean}

Most commonly used measure of central tendency.

Used in interval or ratio scales.

\subsubsection{How to compute:}\label{how-to-compute}

Compute the sum of all scores (∑)

Divide the sum by the number of scores.

In manuscripts, the sample mean is identified as ``\emph{M}''

The sum (∑) of all scores (X) = (∑X)

4 + 5 + 3 = 12

Divide the sum by the number of scores (N) = (∑X/N)

12/3 = 4

Weekly high temperatures in Chicago last winter:

29, 31, 28, 32, 29, 27, 55

What was the average high temperature in Chicago last winter?

All distances below the mean are equal to all the distances above the
mean.

Changing any score (adding or subtracting) will influence the mean.

\subsubsection{When you shouldn't use the
mean}\label{when-you-shouldnt-use-the-mean}

The mean is not appropriate for nominal or ordinal scales.

\begin{itemize}
\tightlist
\item
  It is impossible to calculate.
\end{itemize}

The mean is not appropriate when you have extreme scores (outliers).

\begin{itemize}
\tightlist
\item
  The mean will be pulled towards the extreme score, rendering it no
  longer representative of the rest of the data.
\end{itemize}

The mean is not appropriate when there is missing data

\subsection{The Median}\label{the-median}

Scores are listed in order from smallest to largest

The median is the midpoint, it equally divides the scores

When you have an even number of scores you take the average of the two
middle scores.

The median can be used on ordinal, interval, or ratio scales.

The median is unaffected by extreme scores (outliers).

Weekly high temperatures in Chicago last winter:

29, 31, 28, 32, 29, 27, 55

What was the median temperature in Chicago last winter?

\subsection{The Mode}\label{the-mode}

The most frequently occurring score.

Can be used on ALL scales of measurement.

Weekly high temperatures in Chicago last winter:

29, 31, 28, 32, 29, 27, 55

What was the mode temperature in Chicago last winter?

\bookmarksetup{startatroot}

\chapter{Measurement}\label{measurement}

\section{Measurement}\label{measurement-1}

\textbf{Measurement Error}

Variability in scores due to factors that distort the true score.

\textbf{True Score}

The score a participant would obtain if a measure were perfect and we
could measure without error.

Measurement error + True Score = Observed score

\section{Sources of Measurement
Error}\label{sources-of-measurement-error}

\textbf{Transient States}

Temporary state

\emph{Ex. mood}

\textbf{Stable Attribute}

A lasting state

\emph{Ex. Ambitious personality}

\textbf{Situational factor}

Research setting (Ex. Noise/temperature in the room)

\textbf{Characteristics of the measure}

The measure itself is ambiguous or too long

\textbf{Mistakes in recording}

Incorrect data

\section{Reliability}\label{reliability}

Consistency/dependability of the measuring technique

Inverse relationship with measurement error

If observed score is close to the true score, your measure has high
reliability

Can be assessed using several measurements of the same behavior and
comparing to see if they resulted in similar scores (typically through a
correlation)

\textbf{Correlation Coefficient}

Value that describes relationship between two measures

Ranges from -1.00 to +1.00, sign indicates direction

Correlation of .00 indicates no relationship

\section{Forms of Reliability}\label{forms-of-reliability}

\textbf{Inter-rater Reliability}

Consistency among two or more researchers who observe and record
participants' behavior

\textbf{Test-Retest Reliability}

Consistency of responses on a measure over time, use the same measure
twice and evaluate the correlation.

The results of a reliable measure should not change over time.

\textbf{Inter-Item Reliability}

Consistency between items on a scale.

Tells the researcher whether the items on the scale are measuring the
same thing

If the items do not measure the same thing, measurement error increases
and reliability decreases.

\section{Indices of Inter-Item
Reliability}\label{indices-of-inter-item-reliability}

\textbf{Item-total correlation}

The correlation between one item and the sum of all other items on a
scale.

\textbf{Split-half reliability}

Divide items on a scale into two sections and examine the correlation
between the sections.

\textbf{Cronbach's Alpha (α)}

The average of all possible split-half reliabilities

Most frequently used

α \textgreater{} .70 considered acceptable

\section{Increasing Reliability}\label{increasing-reliability}

Standardize how measure is administered

Clarify instructions and questions

Train researchers/coders

Minimize errors in coding data

\section{Validity}\label{validity}

How accurate is a measure at estimating what it is attempting to assess?

Do differences in scores truly reflect differences in what you are
trying to measure?

\section{Forms of Validity}\label{forms-of-validity}

\textbf{Face Validity}

The extent to which an assessment appears to describe what it is
supposed to measure.

Does not actually impact the ``true'' validity

\textbf{Construct Validity}

How well does a measurement of a hypothetical construct relate to other
measures.

\begin{itemize}
\item
  \textbf{Hypothetical Construct}

  \begin{itemize}
  \item
    Something that cannot be directly observed, but is inferred based on
    observation or experience.
  \item
    \emph{Ex. Personality, Confidence}
  \end{itemize}
\end{itemize}

\textbf{Convergent Validity}

A measure correlates with other measures that it should correlate with

\textbf{Discriminant Validity}

A measure does not correlate with other measures that it should not
correlate with

\section{Bias}\label{bias}

\textbf{Test Bias}

When the validity of a measure is lower for some groups than others.

\bookmarksetup{startatroot}

\chapter{Variability}\label{variability}

NEED RAFALIB PACKAGE

\section{Variability}\label{variability-1}

A quantitative measure of difference between a set of scores that
describes how scores are scattered around a central point.

\textbf{Descriptive Variability}

Assesses spread or clustering of scores.

\textbf{Inferential Variability}

Assesses how accurately one individual score/sample represents the
population.

Used to detect patterns, variability influences how easily those
patterns are detected.

Variability can be small or large.

Small indicates that scores are very clustered together.

Large indicates that scores are widely dispersed.

\section{Measures of Variability}\label{measures-of-variability}

\subsection{Range}\label{range}

Total distance covered by the distribution, from highest to lowest
value, also gives information about how many categories there are.

Relies on two values (extremes), ignores all others

Range = Maximum Score -- Minimum Score

\subsubsection{Calculate in R}\label{calculate-in-r}

Let's use R to work out an example. First, use the \texttt{sample}
function to create 10 scores from 1:10 and assign that list of numbers
(called a vector) to the object `x'.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# random sample of 10 scores from 1{-}10}
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The \texttt{range} function will produce the two values we use to
calculate the range, the highest and lowest.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# gives us the extreme values}
\FunctionTok{range}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

The \texttt{max} and \texttt{min} function will give us the largest and
smallest numbers respectively.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# gives us the maximum value}
\FunctionTok{max}\NormalTok{(x)}

\CommentTok{\# gives us the minimum value}
\FunctionTok{min}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

Now we can use these functions to calculate the mean.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{max}\NormalTok{(x) }\SpecialCharTok{{-}} \FunctionTok{min}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\subsection{Variance \& Standard
Deviation}\label{variance-standard-deviation}

Calculated using all scores in a distribution

Most commonly used measure of variability

Describes average distance between a score and the mean

Used with interval and ratio scales

variance definition of variance

standard deviation definition of standard deviation

\subsubsection{Calculate by hand}\label{calculate-by-hand}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Calculate the mean.
\item
  Subtract the mean from each individual score to get a difference score
  for each participant. Make sure that if you add all of the difference
  scores they equal zero.
\item
  Square the difference scores to get squared scores.
\item
  Add all of the squared scores to get the Sum of Squared Deviations
  (SS).
\item
  Divide the SS by the size of your population (N) or sample (n-1) to
  get the variance (σ\^{}2 or s\^{}2).
\item
  Find the square root of σ\^{}2 to find the standard deviation(σ or s).
\end{enumerate}

\subsubsection{Calculate in R (long)}\label{calculate-in-r-long}

Start with a simple vector we will store in the object `y'.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# data}
\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calculate the mean.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Subtract the mean from each individual score to get a difference score
  for each participant. Make sure that if you add all of the difference
  scores they equal zero.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diff\_score }\OtherTok{\textless{}{-}}\NormalTok{ y }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Square the difference scores to get squared scores.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sq\_score }\OtherTok{\textless{}{-}}\NormalTok{ diff\_score}\SpecialCharTok{\^{}}\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Add all of the squared scores to get the Sum of Squared Deviations
  (SS).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SS }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(sq\_score)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Divide the SS by the size of your population (N) or sample (n-1) to
  get the variance (σ\^{}2 or s\^{}2).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# variance for a population}
\NormalTok{pop\_var }\OtherTok{\textless{}{-}}\NormalTok{ SS}\SpecialCharTok{/}\FunctionTok{length}\NormalTok{(y)}

\CommentTok{\# variance for a sample }
\NormalTok{sample\_var }\OtherTok{\textless{}{-}}\NormalTok{ SS}\SpecialCharTok{/}\NormalTok{(}\FunctionTok{length}\NormalTok{(y) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Find the square root of σ\^{}2 to find the standard deviation(σ or s).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# population standard deviation}
\FunctionTok{sqrt}\NormalTok{(pop\_var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1.414214
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sample standard deviation}
\FunctionTok{sqrt}\NormalTok{(sample\_var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1.581139
\end{verbatim}

\subsubsection{Calculate in R (short)}\label{calculate-in-r-short}

Start with the same data

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# data}
\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calculate variance. For the calculation of population variance and
  standard deviation we can use the \texttt{rafalib} package. For
  populations we will use the \texttt{popvar} function and for sample
  vaiance we will use the \texttt{var} function from base R.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# population variance}
\FunctionTok{library}\NormalTok{(rafalib)}
\FunctionTok{popvar}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sample variance}
\FunctionTok{var}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 2.5
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Calculate stabdard deviation
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# population stabdard deviation}
\FunctionTok{popsd}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1.414214
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sample sd}
\FunctionTok{sd}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1.581139
\end{verbatim}

\section{Population v Sample}\label{population-v-sample}

Population is EVERYONE.

Variance (σ\^{}2) = SS/N

Standard Deviation (σ) = √(SS/N)

Sample is a subset of everyone.

Variance (s2) = SS/n-1.

Standard Deviation (s) = √(SS/(n-1)).

We use a different formula for samples because we are using limited
information from a small group (the sample) to draw inferences about a
larger group (the population).

Samples have less variability than populations.

\section{Biased and Unbiased
Statistics}\label{biased-and-unbiased-statistics}

\textbf{Biased Statistics}

The average value overestimates or underestimates the population
parameter

i.e.~the sample before adjustment (n-1)

\textbf{Unbiased Statistics}

The average value is equal to the population parameter.

i.e.~the sample after adjustment (n-1).

\section{Transforming Data Sets}\label{transforming-data-sets}

\subsection{Adding a constant}\label{adding-a-constant}

When you add a value to every score in the data set it does not change
the standard deviation. Try it out calculate the sample standard
deviation of the example object.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{example\_1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)}

\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(example\_1)}
\NormalTok{s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1.581139
\end{verbatim}

Now, let's add a constant value of 2 to every score in the example
object.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{example\_2 }\OtherTok{\textless{}{-}}\NormalTok{ example\_1 }\SpecialCharTok{+} \DecValTok{2}
\NormalTok{example\_2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3 4 5 6 7
\end{verbatim}

Let's see if the sample standard deviation has changed.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(example\_2)}
\end{Highlighting}
\end{Shaded}

There is no difference because the distance between scores is unchanged.
The shape of the distribution is the same, just shifted to the right.

\pandocbounded{\includegraphics[keepaspectratio]{variability_files/figure-pdf/unnamed-chunk-19-1.pdf}}

\subsection{Multiplying by a constant}\label{multiplying-by-a-constant}

When you multiply every score in the data set by a constant changes
standard deviation. Try it out. Calculate the sample standard deviation
of the example object.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{example\_1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)}

\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(example\_1)}
\NormalTok{s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1.581139
\end{verbatim}

Now, let's multiply every score in the dataset by a contant of 3.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{example\_2 }\OtherTok{\textless{}{-}}\NormalTok{ example\_1 }\SpecialCharTok{*} \DecValTok{3}
\NormalTok{example\_2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1]  3  6  9 12 15
\end{verbatim}

Let's see if the sample standard deviation has changed.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(example\_2)}
\NormalTok{s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 4.743416
\end{verbatim}

There distributions now look very different. The distance between scores
in the \texttt{example\_2} object has changed by a multiple of 3. The
distance between scores is now greater, resulting in a wider
distribution.

\pandocbounded{\includegraphics[keepaspectratio]{variability_files/figure-pdf/unnamed-chunk-23-1.pdf}}

\bookmarksetup{startatroot}

\chapter{Selecting participants}\label{selecting-participants}

\section{Sampling}\label{sampling}

Difficult to study everyone (population)

\emph{Ex. Every single person with PTSD}

\textbf{Probability Samples}

Can quantify the likelihood of being selected because we know how many
people are in the population of interest

Know selection probability

Accurately describes a population

Must be representative of the population

Rarely used in behavioral sciences

\emph{Ex. A 1 in a million chance of winning the lottery}

\textbf{Non-Probability}

Can't quantify the likelihood of being selected, probably because we
don't know how many people are in the population being measured.

\section{Error of Estimation}\label{error-of-estimation}

Samples rarely mirror the population perfectly

The difference between them is called sampling error

Sampling error can be estimated for probability samples because we know
the population size

\section{Probability sampling}\label{probability-sampling}

\section{Types of Probability
Sampling}\label{types-of-probability-sampling}

\textbf{Simple Random Sampling}

Known Population

Random Selection

Equal selection probability for every sample

\emph{Ex. Pulling a name out of a hat}

Require a \textbf{sampling frame}

\begin{itemize}
\tightlist
\item
  An outline of the people you will be sampling from
\end{itemize}

\emph{ex. USI students enrolled in Introduction to Psychology this year}

\textbf{Systematic Sampling}

Not concerned with population size

Every \emph{n}th person gets chosen

It is not random, a system is used to choose participants

\emph{Ex. The every third person who enters the classroom gets to
participate in an experiment}

\textbf{Stratified Random Sampling}

Divide population into groups based on a shared characteristic (called
\textbf{strata})

Randomly sample people from each strata

This sampling method ensures an adequate number of participants from
each group

\emph{Ex. Separate participants into groups based on major, then take 5
random participants from those strata}

\textbf{Clustered Sampling}

Clusters occur naturally

Sample the clusters, then sample participants

More efficient than stratified random sampling because only the clusters
are sampled

Clusters are essentially the same as one another, whereas strata are
fundamentally different

\emph{Ex. Randomly sample 5 of the counties in Illinois, then randomly
sample the participants in those counties.}

\section{Issues with Probability
Sampling}\label{issues-with-probability-sampling}

\textbf{Non-response}

Some participants do not respond, these participants may be different in
some important way from those that do respond

\textbf{Misgeneralization}

Generalizing to the wrong population

\section{Non-probability Samples}\label{non-probability-samples}

Can't calculate selection probability

Not random

Used to study relationships among variables

Behavioral sciences use non-probability samples most often

\subsection{Types of Non-probability
Samples}\label{types-of-non-probability-samples}

\textbf{Convenience Sampling}

Uses participants that are easy to obtain

Most typical type of non-probability sampling

Replication of experiments shows generalizability

\textbf{Quota Sampling}

Specific proportions of people with selected characteristics are
selected

Often used for market research

\emph{Ex: 20 USI students who enjoy hiking}

\textbf{Snowball Sampling}

Used for hard to reach groups

Can use incentives (cautiously) to increase response

\emph{Ex: For every person you bring in to the experiment I will give
you 5 dollars}

\section{How Many Participants is
Enough?}\label{how-many-participants-is-enough}

Economic samples are typical, only collect as much data as needed.

Determine how many are needed via a power analysis.

Aim for reasonable accuracy and cost for the scope of the project.

\bookmarksetup{startatroot}

\chapter{Ethical Issues in Behavioral
Research}\label{ethical-issues-in-behavioral-research}

\section{Researcher Obligations}\label{researcher-obligations}

Enhance Understanding

Protect participants

Ethical questions arise when enhancing understanding and protecting
participants conflict

\section{Some approaches to ethical
decisions}\label{some-approaches-to-ethical-decisions}

Deontology

Ethical decisions are made based on a moral code

Utilitarianism

Ethical decisions are made based on weighing the benefits and
consequences

Ethical Skepticism

Belief that a concrete moral code cannot exist

\subsection{Benefits of
Utilitarianism}\label{benefits-of-utilitarianism}

Basic knowledge

Improved techniques

Practical outcomes

Benefits for researchers

Benefits for participants

\subsection{Costs of Utilitarianism}\label{costs-of-utilitarianism}

Time and effort

Participant's welfare

Money

Deception; creating distrust

\section{Institutional Review Board
(IRB)}\label{institutional-review-board-irb}

Scientific and nonscientific board members

Researchers describes purpose, procedures, and risks

IRB must approve study before it can be conducted

\section{Lack of adequate informed
consent}\label{lack-of-adequate-informed-consent}

Informed consent is a disclosing of the nature of participation

A researcher must obtain explicit agreement from participants

Possible problems:

Compromise study validity

Some participants are unable to consent

\section{Ethical Considerations}\label{ethical-considerations}

\subsection{Invasion of privacy}\label{invasion-of-privacy}

Participants may decide when, where, to whom, and what responses to
reveal

Public observation is not an invasion of privacy

\subsection{Coercion}\label{coercion}

Pressure to participate from an authority figure

To prevent coercion, alternate activity must be available to opt of out
research

\subsection{Potential Harm}\label{potential-harm}

Pain, stress, failure, anxiety, or other negative emotions

Minimal risk -- no greater than that ordinarily encountered

More than minimal risk requires strong justification

\subsection{Deception}\label{deception}

False purpose of study

Experimental Confederate

False feedback

Presenting related studies as unrelated

Giving incorrect information regarding stimulus materials

\subsection{Violation of
Confidentiality}\label{violation-of-confidentiality}

Data may only be used for research

Data may not be disclosed to others

Anonymity is the easiest way to ensure confidentiality

\subsection{Debriefing}\label{debriefing}

Clarify nature of study

Remove any stress or negative study-indices consequences

Obtain participant reactions

Ensure participants leave feeling good about participation

\subsection{Vulnerable Populations}\label{vulnerable-populations}

Children

Prisoners

People with impaired decision making

People at risk for suicide

Pregnant women, fetuses, newborns

\subsection{Scientific Misconduct}\label{scientific-misconduct}

Fabrication, falsification, plagiarism

Questionable research practices

Unethical behavior

\bookmarksetup{startatroot}

\chapter{z scores}\label{z-scores}

\section{z-Scores and Location}\label{z-scores-and-location}

Raw scores provide very little information by themselves

Ex. Terrence got 34 points on the test. Did he do well?

The mean and standard deviation provide a context with which to
interpret the raw score.

Ex. Archibald's class average was 75 points with a 2 point standard
deviation. His score of 34 is not very good.

z-scores tell us where an x value is in relation to the mean and
standard deviation with one number.

\section{Z-scores}\label{z-scores-1}

Signed (+ or -) number

The sign tells you whether the x value is above the mean (positive) or
below the mean (negative)

The number tells you the amount of standard deviations between the raw
score and the mean of the distribution

Ex: What does a z-score of \_\_\_\_\_\_\_\_ mean: -1? +2? -3?

\section{Z-score Formula}\label{z-score-formula}

\section{Z-scores as a Standard
Distribution}\label{z-scores-as-a-standard-distribution}

z-scores do not change the shape of the original distribution or the
location of a score relative to others

When x values are transformed into z-scores, the resulting distribution:

The mean is always zero

The standard deviation is always one

Most z-scores are between z = -2.00 and z = +2.00

\section{Z-scores and Locations}\label{z-scores-and-locations}

As descriptive statistics, describe exactly where an individual is
located

As inferential statistics, determine whether a sample is representative
of its population

\section{Z-scores and Samples}\label{z-scores-and-samples}

Z-scores are standardized, so we can compare different distributions.

\bookmarksetup{startatroot}

\chapter{Probability}\label{probability}

\section{Probability}\label{probability-1}

The likelihood of all possible outcomes

``Probability'' = p

Can use fractions, decimals, or percentages:

p = ½ = .50 = 50\%

Goes from 0\% - 100\% or 0 -- 1

Equals the desired outcome divided by all possible outcomes

\section{Probability \& Sampling}\label{probability-sampling-1}

Samples are used in inferential statistics, to make inferences about
larger populations

Probability can be used to quantify the relationship between samples and
population

When something occurs in a sample, how likely is it that it represents
the population?

Probability calculation requires independent random sampling, has an
equal probability of being selected and replacement

\section{Probability and Inferential
Statistics}\label{probability-and-inferential-statistics}

Low probability values = Special/Rare, not common or likely to happen

High probability values = Common/likely to happen

In terms of finding an effect:

Low probability = effect

Means your finding is unlikely to happen by chance, there is a different
cause

High probability = no effect

Means your finding is common or likely to happen

\section{Probability and Frequency
Distributions}\label{probability-and-frequency-distributions}

If a distribution displays a population of scores a portion of the graph
represents a portion of the population

Probability can be defined by a proportion of the graph

Can determine this by using the z-score and the unit normal table

\bookmarksetup{startatroot}

\chapter{Distribution of Sample
Means}\label{distribution-of-sample-means}

\section{Samples vs.~Populations}\label{samples-vs.-populations}

Though most behavioral science uses sample to test hypotheses, often
times those hypotheses are about populations.

A sample is not a perfect representation of a population, so any
statistics you calculate for that sample are also not representative of
the population.

Sampling Error

The difference between sample statistics and population parameters.

\section{Sampling Distributions}\label{sampling-distributions}

Sampling Distribution

A distribution of statistics of all possible samples of a given size
from a population

One example of a sampling distribution is\ldots..

Distribution of Sample Means

A collection of sample means for all possible random samples of a given
size that could be obtained from a population.

A distribution of sample means should form a normal distribution, with
most of the sample means grouping around the population mean if the
number of scores in each sample is more than 30.

Larger sample are more representative of populations than smaller
samples.

The mean of the distribution of sample means is the same as the
population mean.

\section{Standard Error of the Mean}\label{standard-error-of-the-mean}

The standard deviation of the distribution of sample means is the

Standard Error of the Mean

𝜎𝑀= 𝜎𝑛√ 𝜎 M =

𝜎 n

\section{Z-score for a Sample}\label{z-score-for-a-sample}

By using a sampling distribution you can calculate the location of an
entire sample within a population

z = M - µ

σM

\bookmarksetup{startatroot}

\chapter{Hypothesis Testing}\label{hypothesis-testing}

\section{Purpose of Hypothesis
Testing}\label{purpose-of-hypothesis-testing}

Behavioral scientists often can't measure all individuals in a
population.

\emph{Ex. Measuring the inhibition of all lawyers in the United States}

Use samples to test a hypothesis that is made about the population.

Expose a sample to your IV, evaluate the results, and make an inference
that the same effect would be seen in the population if you could
actually measure everyone.

Hypothesis testing takes several steps

\section{Steps of Hypothesis Testing}\label{steps-of-hypothesis-testing}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  State the Hypothesis

  \begin{itemize}
  \tightlist
  \item
    \textbf{Null Hypothesis}

    \begin{itemize}
    \tightlist
    \item
      H0
    \item
      The treatment had no effect on the DV
    \end{itemize}
  \item
    \textbf{Alternative Hypothesis}

    \begin{itemize}
    \tightlist
    \item
      H1
    \item
      The treatment does have an effect on the DV
    \end{itemize}
  \end{itemize}
\item
  Set the decision criteria

  \begin{itemize}
  \tightlist
  \item
    \textbf{Alpha (α)}
  \item
    The alpha value tells us how willing we are to make a mistake (as
    there is never a flawless study) and what probability of error we
    are willing to accept.
  \item
    In social sciences less than 5\% probability (p) is acceptable
  \item
    α = .05 = 5\% = 5/100
  \item
    Probability of error (p) should be \textless{} .05
  \end{itemize}
\item
  Collect data and compute statistic

  \begin{itemize}
  \tightlist
  \item
    T test, Correlation, ANOVA
  \end{itemize}
\item
  Make a decision

  \begin{itemize}
  \tightlist
  \item
    Can reject the null hypothesis or fail to reject the null hypothesis
  \item
    \textbf{Reject the Null hypothesis}

    \begin{itemize}
    \tightlist
    \item
      Claims there no significant effect
    \end{itemize}
  \item
    \textbf{Fail to Reject the Null Hypothesis}

    \begin{itemize}
    \tightlist
    \item
      Claims there is a significant effect
    \end{itemize}
  \item
    There is a 5\% chance of making a mistake (false positive or false
    negative)
  \end{itemize}
\end{enumerate}

\section{Decision Making Errors}\label{decision-making-errors}

\textbf{Type 1 Error (False Positive)}

Rejecting a true Null hypothesis, claiming there is a significant effect
when there really is not.

\emph{Ex. Claiming that a medical treatment will cure cancer, but it
does not.}

\textbf{Type II Error (False Negative)}

Failing to reject a false Null Hypothesis, claiming there is not a
significant effect when there really is.

\emph{Ex. Claiming there is no difference between smokers and
non-smokers, but there really is.}

\section{Hypothesis Testing Table}\label{hypothesis-testing-table}

Use this table to help you determine whether the correct decision has
been made about the Null and Alternative Hypotheses.

\section{Assumptions of Hypothesis
Testing}\label{assumptions-of-hypothesis-testing}

The variability of scores and the number of scores in a sample influence
the results of a hypothesis test, so several assumptions must be met
before conducting one.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Must have random sampling
\item
  Must have independent observations
\item
  The value of sigma must remain unchanged by the treatment
\item
  The data must form a normal sampling distribution
\end{enumerate}

\bookmarksetup{startatroot}

\chapter{T-tests}\label{t-tests}

\section{Introduction}\label{introduction-2}

This chapter will be teaching you about a T-test and the use we have for
them in psychology and also the real life applications there are when we
use them. T-tests are a very useful tool when it comes to inferential
statistics and they allow us to compare means and to also determine if
group differences that we observe are statistically significant. In this
chapter you will learn how to:

\begin{itemize}
\item
  Run one sample and independent sample t-tests and paired t-test.
\item
  perform t-tests using R and interpret them
\item
  find different assumptions like normality and homogeneity of variance
\item
  create apa style results using the \texttt{report} and
  \texttt{apaTables} packages
\end{itemize}

\section{Pre-requisites}\label{pre-requisites}

This chapter will be using different packages in R to make calculating
t-tests easier. One function we will be using is the \texttt{t\_test}
function from the \texttt{rstatix} package which utilizes the following
formula (x = DV \textasciitilde{} 1, mu = number). The 1 after the
\textasciitilde{} is used for one sample t tests because we aren't
comparing two samples. You will also need to load up the following
packages.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
v dplyr     1.1.4     v readr     2.1.6
v forcats   1.0.1     v stringr   1.6.0
v ggplot2   4.0.1     v tibble    3.3.0
v lubridate 1.9.4     v tidyr     1.3.1
v purrr     1.2.0     
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rstatix)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'rstatix'

The following object is masked from 'package:stats':

    filter
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(report)}
\FunctionTok{library}\NormalTok{(apaTables)}
\end{Highlighting}
\end{Shaded}

\textbf{TIP:} Make note of the warning that comes after loading
\texttt{rstatix} because it says that the use of the \texttt{filter()}
function now falls under the use of rstatix so the regular stats filter
must be called directly if you want to use it but we will be using
rstatix in this chapter.

\section{What is a t-test?}\label{what-is-a-t-test}

Now before we get into working inside of R using t-tests first we have
to understand what they are and some different ways we use them. A
t-test is a inferential statistic that compares \textbf{means} while
also making note of variability and sample sizes. There are different
ways in psychology that we can use these tests.

\subsection{One-sample t-test}\label{one-sample-t-test}

When we want to compare one group against a known value like for example
the population average this is when we will use a one-sample t-test
because we are only taking one group and applying it to a value that is
already known.

\subsection{Independent-sample t-test}\label{independent-sample-t-test}

Now when we want compare two completely different groups like say for
example gender using males and females this is where we will use the
independent sample t-test because the two are independent from each
other and results will not rely on the other.

\subsection{Paired t-test}\label{paired-t-test}

We use a paired t-test when we want to examine one group that usually
experiences a change so lets say for example we want to measure a groups
stress levels before and after listening to music we would use a paired
t-test

\subsection{Now lets practice creating a small data-set that we could
see in a real study that you might do for your
project.}\label{now-lets-practice-creating-a-small-data-set-that-we-could-see-in-a-real-study-that-you-might-do-for-your-project.}

Lets say a researcher wants to see if listening to calming music will
help reduce stress. In the experiment stress is measured on a scale of
0-100.

The hypothesis for this example is that students who listen to music
will report lower stress levels.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stress\_data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{group =} \FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Control"}\NormalTok{, }\DecValTok{8}\NormalTok{), }\FunctionTok{rep}\NormalTok{(}\StringTok{"Music"}\NormalTok{, }\DecValTok{8}\NormalTok{)),}
  \AttributeTok{stress =} \FunctionTok{c}\NormalTok{(}\DecValTok{75}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{78}\NormalTok{, }\DecValTok{82}\NormalTok{, }\DecValTok{79}\NormalTok{, }\DecValTok{76}\NormalTok{, }\DecValTok{81}\NormalTok{, }\DecValTok{74}\NormalTok{, }
             \DecValTok{60}\NormalTok{, }\DecValTok{65}\NormalTok{, }\DecValTok{62}\NormalTok{, }\DecValTok{58}\NormalTok{, }\DecValTok{63}\NormalTok{, }\DecValTok{61}\NormalTok{, }\DecValTok{59}\NormalTok{, }\DecValTok{64}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Descriptive Statistics}\label{descriptive-statistics}

Now we are going to go through some practice examples to help you get a
better use of applying different t-tests to scenarios

\subsection{Example using data}\label{example-using-data}

Now lets run through an example fo using a one sample t-test in a
psychology example

Does the average stress level in the \textbf{music} group differ from
the control group?

First we must separate the music only group into their own section from
the control group then use the \texttt{get\_summary\_stats} function to
get a summary of the stats from our previous data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stress\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(group) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{get\_summary\_stats}\NormalTok{(stress, }\AttributeTok{type =} \StringTok{"mean\_sd"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 2 x 5
  group   variable     n  mean    sd
  <chr>   <fct>    <dbl> <dbl> <dbl>
1 Control stress       8  78.1  2.9 
2 Music   stress       8  61.5  2.45
\end{verbatim}

As you can see in the output above the results suggest that the people
in the music group are less stressed than the people in the control
group.

\subsection{Assumption Testing}\label{assumption-testing}

Now that we have our data it is important that we check to see if it is
normal enough for a t-test by using the Shapiro-wilk test by using our
stress variable

\subsection{Shapiro-Wilk test}\label{shapiro-wilk-test}

Now we must use the Shapiro-wilk test to see if p \textgreater{} .05.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stress\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(group) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{shapiro\_test}\NormalTok{(stress)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 2 x 4
  group   variable statistic     p
  <chr>   <chr>        <dbl> <dbl>
1 Control stress       0.954 0.753
2 Music   stress       0.975 0.933
\end{verbatim}

As you can see that our p value is \textgreater{} than .05 so we can now
run a t-test on it.

\section{Independent Sample t-test}\label{independent-sample-t-test-1}

Now lets take the data from before and use an independent sample t-test
to see if our p value is \textless{} .05 making it significant.

\subsection{Homogeneity of Variance}\label{homogeneity-of-variance}

We need to use the homogeneity of variance test which is the
\texttt{levene\_test} for independent t-tests to see if we are able to
conduct a t-test on our data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stress\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{levene\_test}\NormalTok{(stress }\SpecialCharTok{\textasciitilde{}}\NormalTok{ group)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 1 x 4
    df1   df2 statistic     p
  <int> <int>     <dbl> <dbl>
1     1    14     0.317 0.583
\end{verbatim}

As you see in the output our F-value for this test is .317 which shows
how the group variance is different compared to each other. So a low
F-value means that variance is similar.

The p-value of .583 shows us that our assumption is met because variance
is equal between groups.

\subsection{Practice with independent
sample}\label{practice-with-independent-sample}

Lets now take our data and run it through a t-test

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t\_test}\NormalTok{(stress\_data, stress }\SpecialCharTok{\textasciitilde{}}\NormalTok{ group)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 1 x 8
  .y.    group1  group2    n1    n2 statistic    df            p
* <chr>  <chr>   <chr>  <int> <int>     <dbl> <dbl>        <dbl>
1 stress Control Music      8     8      12.4  13.6 0.0000000085
\end{verbatim}

As you see in our output we get a lot of data so lets analyze each part
of the output

You can see in \texttt{group1} that this is the control group and
\texttt{group2} is the music group.

The \texttt{n1} and \texttt{n2} represent the participant number in each
group which for this data set is 8

The t stat you can find under \texttt{statistic} this is 12.38 and it is
a large t value which suggests a big difference between the variability
of scores from the groups.

Our p value for this test is 8.5e-09. This is a very small p value which
indicates a statistically significant result which means that we reject
the null hypothesis fro this experiment.

\subsection{APA Conclusion}\label{apa-conclusion}

Now lets write a APA conclusion for the output that we have just
analyzed above.

\textbf{\emph{Participants in the music group reported significantly
lowered stress (M = 12.38, SD = 2.45) than the control group ( M =
13.61, SD = 2.90), t(16) = 12.38, p \textless{} .05.}}

\section{One Sample t-test}\label{one-sample-t-test-1}

Now we can use the same data we just used to compare the mean from one
group to a known population mean

\subsection{Running the t-test}\label{running-the-t-test}

Now lets take the music group and use the known population mean which
will be 70 in this example and compare that to the means of the people
in our data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{music\_only }\OtherTok{\textless{}{-}}\NormalTok{ stress\_data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(group }\SpecialCharTok{==} \StringTok{"Music"}\NormalTok{)}
\FunctionTok{t\_test}\NormalTok{(music\_only, stress }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{, }\AttributeTok{mu =} \DecValTok{70}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 1 x 7
  .y.    group1 group2         n statistic    df         p
* <chr>  <chr>  <chr>      <int>     <dbl> <dbl>     <dbl>
1 stress 1      null model     8     -9.81     7 0.0000242
\end{verbatim}

You can see in this output that our sample mean is below the population
mean we compared it to by seeing our statistic is \texttt{-9.81}
suggesting a large difference relative to variability. We also have a
smaller p value than .05 so it means we can reject the null and that our
sample mean differs from the population mean.

\section{Paired t-test}\label{paired-t-test-1}

We use a paired t-test when we want to examine two scores before and
after a group receives a stimulus.

So lets now do some practice imaging that we weant to see students
stress levels before and after listening to some calming music

\subsection{Practice Problem}\label{practice-problem}

First we need to create our data frame so we can use our data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{paired\_data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{student =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{8}\NormalTok{,}
  \AttributeTok{stress\_before =} \FunctionTok{c}\NormalTok{(}\DecValTok{75}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{78}\NormalTok{, }\DecValTok{82}\NormalTok{, }\DecValTok{79}\NormalTok{, }\DecValTok{76}\NormalTok{, }\DecValTok{81}\NormalTok{, }\DecValTok{74}\NormalTok{),}
  \AttributeTok{stress\_after  =} \FunctionTok{c}\NormalTok{(}\DecValTok{60}\NormalTok{, }\DecValTok{65}\NormalTok{, }\DecValTok{62}\NormalTok{, }\DecValTok{58}\NormalTok{, }\DecValTok{63}\NormalTok{, }\DecValTok{61}\NormalTok{, }\DecValTok{59}\NormalTok{, }\DecValTok{64}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Checking for Normality}\label{checking-for-normality}

Now we need to check for normality to see the difference of scores
before and after treatment by using the \textbf{Shapiro} \textbf{wick
test.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{paired\_data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{diff =}\NormalTok{ stress\_before }\SpecialCharTok{{-}}\NormalTok{ stress\_after) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{shapiro\_test}\NormalTok{(diff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 1 x 3
  variable statistic     p
  <chr>        <dbl> <dbl>
1 diff         0.877 0.177
\end{verbatim}

Since we have a p \textgreater{} .05 we can now run our paired t-test.

\subsection{Running the t-test}\label{running-the-t-test-1}

Now we are going to be running our paired t-test to see if stress
significantly decreased from the same participants after they have
received the treatment.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(paired\_data}\SpecialCharTok{$}\NormalTok{stress\_before,}
\NormalTok{       paired\_data}\SpecialCharTok{$}\NormalTok{stress\_after,}
       \AttributeTok{paired =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

    Paired t-test

data:  paired_data$stress_before and paired_data$stress_after
t = 10.673, df = 7, p-value = 1.39e-05
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 12.94169 20.30831
sample estimates:
mean difference 
         16.625 
\end{verbatim}

\subsection{APA Conclusion}\label{apa-conclusion-1}

Now that we have our output from our t-test we can use the
\texttt{report} package to create an APA style conclusion for us
automatically

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{paired\_test }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(paired\_data}\SpecialCharTok{$}\NormalTok{stress\_before,}
\NormalTok{                      paired\_data}\SpecialCharTok{$}\NormalTok{stress\_after,}
                      \AttributeTok{paired =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{report}\NormalTok{(paired\_test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
For paired samples, 'repeated_measures_d()' provides more options.
\end{verbatim}

\begin{verbatim}
Effect sizes were labelled following Cohen's (1988) recommendations.

The Paired t-test testing the difference between paired_data$stress_before and
paired_data$stress_after (mean difference = 16.62) suggests that the effect is
positive, statistically significant, and large (difference = 16.62, 95% CI
[12.94, 20.31], t(7) = 10.67, p < .001; Cohen's d = 3.77, 95% CI [1.71, 5.81])
\end{verbatim}

Our output shows us that the effect is positive and significant and the
treatment was effective.

\section{APA Tables}\label{apa-tables}

APA tables is a very useful package that allows us to present our data
in APA formatted tables

\subsection{Creating an APA Table}\label{creating-an-apa-table}

Now we are going to create an APA table for us to use that combines our
control and music groups.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{apa.1way.table}\NormalTok{(}
  \AttributeTok{data =}\NormalTok{ stress\_data,}
  \AttributeTok{dv =}\NormalTok{ stress,}
  \AttributeTok{iv =}\NormalTok{ group,}
  \AttributeTok{filename =} \StringTok{"stress\_ttest\_table.doc"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}


Descriptive statistics for stress as a function of group.  

   group     M   SD
 Control 78.12 2.90
   Music 61.50 2.45

Note. M and SD represent mean and standard deviation, respectively.
 
\end{verbatim}

As you can see \texttt{APA\ tables} creates a simple and detailed table
that you can put into a word document when you are writing your final
paper.

\section{Report Package}\label{report-package}

The \texttt{report} package automatically formats any data or results
into a APA style sentence that works very will for research papers

It generates an APA style paragraph that you can put right into your
paper

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{report}\NormalTok{(paired\_test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
For paired samples, 'repeated_measures_d()' provides more options.
\end{verbatim}

\begin{verbatim}
Effect sizes were labelled following Cohen's (1988) recommendations.

The Paired t-test testing the difference between paired_data$stress_before and
paired_data$stress_after (mean difference = 16.62) suggests that the effect is
positive, statistically significant, and large (difference = 16.62, 95% CI
[12.94, 20.31], t(7) = 10.67, p < .001; Cohen's d = 3.77, 95% CI [1.71, 5.81])
\end{verbatim}

\bookmarksetup{startatroot}

\chapter*{References}\label{references}
\addcontentsline{toc}{chapter}{References}

\markboth{References}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-knuth84}
Knuth, Donald E. 1984. {``Literate Programming.''} \emph{Comput. J.} 27
(2): 97--111. \url{https://doi.org/10.1093/comjnl/27.2.97}.

\end{CSLReferences}




\end{document}
